//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlyR.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlyR.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only R Application.
        /// </summary>
        public static string ACCESSIBILITY_ONLY_R {
            get {
                return ResourceManager.GetString("ACCESSIBILITY_ONLY_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        public static string APP_VER {
            get {
                return ResourceManager.GetString("APP_VER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to main page.
        /// </summary>
        public static string BACK_TO_MAIN_PAGE {
            get {
                return ResourceManager.GetString("BACK_TO_MAIN_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files copied.
        /// </summary>
        public static string COPIED {
            get {
                return ResourceManager.GetString("COPIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create folder {0}.
        /// </summary>
        public static string CREATE_FOLDER_ERROR {
            get {
                return ResourceManager.GetString("CREATE_FOLDER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start recording.
        /// </summary>
        public static string ERROR_START {
            get {
                return ResourceManager.GetString("ERROR_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not stop recording.
        /// </summary>
        public static string ERROR_STOP {
            get {
                return ResourceManager.GetString("ERROR_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient free space to record.
        /// </summary>
        public static string INSUFFICIENT_FREE_SPACE {
            get {
                return ResourceManager.GetString("INSUFFICIENT_FREE_SPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No limit.
        /// </summary>
        public static string LIFE_0 {
            get {
                return ResourceManager.GetString("LIFE_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Day.
        /// </summary>
        public static string LIFE_1_DAY {
            get {
                return ResourceManager.GetString("LIFE_1_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Month.
        /// </summary>
        public static string LIFE_1_MONTH {
            get {
                return ResourceManager.GetString("LIFE_1_MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Week.
        /// </summary>
        public static string LIFE_1_WEEK {
            get {
                return ResourceManager.GetString("LIFE_1_WEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Year.
        /// </summary>
        public static string LIFE_1_YR {
            get {
                return ResourceManager.GetString("LIFE_1_YR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Days.
        /// </summary>
        public static string LIFE_2_DAYS {
            get {
                return ResourceManager.GetString("LIFE_2_DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Months.
        /// </summary>
        public static string LIFE_2_MONTHS {
            get {
                return ResourceManager.GetString("LIFE_2_MONTHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Weeks.
        /// </summary>
        public static string LIFE_2_WEEKS {
            get {
                return ResourceManager.GetString("LIFE_2_WEEKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Years.
        /// </summary>
        public static string LIFE_2_YRS {
            get {
                return ResourceManager.GetString("LIFE_2_YRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 Months.
        /// </summary>
        public static string LIFE_6_MONTHS {
            get {
                return ResourceManager.GetString("LIFE_6_MONTHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mono.
        /// </summary>
        public static string MONO {
            get {
                return ResourceManager.GetString("MONO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No limit.
        /// </summary>
        public static string NO_LIMIT {
            get {
                return ResourceManager.GetString("NO_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recordings today!.
        /// </summary>
        public static string NO_RECORDINGS {
            get {
                return ResourceManager.GetString("NO_RECORDINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No space on {0}.
        /// </summary>
        public static string NO_SPACE {
            get {
                return ResourceManager.GetString("NO_SPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not recording.
        /// </summary>
        public static string NOT_RECORDING {
            get {
                return ResourceManager.GetString("NOT_RECORDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour.
        /// </summary>
        public static string ONE_HOUR {
            get {
                return ResourceManager.GetString("ONE_HOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 minute.
        /// </summary>
        public static string ONE_MIN {
            get {
                return ResourceManager.GetString("ONE_MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording.
        /// </summary>
        public static string RECORDING {
            get {
                return ResourceManager.GetString("RECORDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordings folder.
        /// </summary>
        public static string RECORDINGS_FOLDER_TOOLTIP {
            get {
                return ResourceManager.GetString("RECORDINGS_FOLDER_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart OnlyR after changing the language..
        /// </summary>
        public static string RESTART_LANGUAGE {
            get {
                return ResourceManager.GetString("RESTART_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save today&apos;s recordings to drive {0}.
        /// </summary>
        public static string SAVE_TO_DRIVE {
            get {
                return ResourceManager.GetString("SAVE_TO_DRIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save today&apos;s recordings to drives {0}.
        /// </summary>
        public static string SAVE_TO_DRIVES {
            get {
                return ResourceManager.GetString("SAVE_TO_DRIVES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Recording Folder.
        /// </summary>
        public static string SELECT_DEST_FOLDER {
            get {
                return ResourceManager.GetString("SELECT_DEST_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow close when recording.
        /// </summary>
        public static string SETTINGS_ALLOW_CLOSE {
            get {
                return ResourceManager.GetString("SETTINGS_ALLOW_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always on top.
        /// </summary>
        public static string SETTINGS_ALWAYS_ON_TOP {
            get {
                return ResourceManager.GetString("SETTINGS_ALWAYS_ON_TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit rate.
        /// </summary>
        public static string SETTINGS_BIT_RATE {
            get {
                return ResourceManager.GetString("SETTINGS_BIT_RATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels.
        /// </summary>
        public static string SETTINGS_CHANNELS {
            get {
                return ResourceManager.GetString("SETTINGS_CHANNELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fade out recordings.
        /// </summary>
        public static string SETTINGS_FADE_OUT {
            get {
                return ResourceManager.GetString("SETTINGS_FADE_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre (in MP3 tag).
        /// </summary>
        public static string SETTINGS_GENRE {
            get {
                return ResourceManager.GetString("SETTINGS_GENRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use loopback capture.
        /// </summary>
        public static string SETTINGS_LOOPBACK_CAPTURE {
            get {
                return ResourceManager.GetString("SETTINGS_LOOPBACK_CAPTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max recording time.
        /// </summary>
        public static string SETTINGS_MAX_RECORDING_TIME {
            get {
                return ResourceManager.GetString("SETTINGS_MAX_RECORDING_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording device.
        /// </summary>
        public static string SETTINGS_RECORDING_DEVICE {
            get {
                return ResourceManager.GetString("SETTINGS_RECORDING_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording lifetime.
        /// </summary>
        public static string SETTINGS_RECORDING_LIFETIME {
            get {
                return ResourceManager.GetString("SETTINGS_RECORDING_LIFETIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordings....
        /// </summary>
        public static string SETTINGS_RECORDINGS_BTN {
            get {
                return ResourceManager.GetString("SETTINGS_RECORDINGS_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordings folder.
        /// </summary>
        public static string SETTINGS_RECORDINGS_FOLDER {
            get {
                return ResourceManager.GetString("SETTINGS_RECORDINGS_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample rate.
        /// </summary>
        public static string SETTINGS_SAMPLE_RATE {
            get {
                return ResourceManager.GetString("SETTINGS_SAMPLE_RATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silence detection (% of full volume).
        /// </summary>
        public static string SETTINGS_SILENCE_AS_PERCENTAGE_VOLUME {
            get {
                return ResourceManager.GetString("SETTINGS_SILENCE_AS_PERCENTAGE_VOLUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start minimised.
        /// </summary>
        public static string SETTINGS_START_MINIMIZED {
            get {
                return ResourceManager.GetString("SETTINGS_START_MINIMIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start recording on launch.
        /// </summary>
        public static string SETTINGS_START_ON_LAUNCH {
            get {
                return ResourceManager.GetString("SETTINGS_START_ON_LAUNCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop on a period of silence.
        /// </summary>
        public static string SETTINGS_STOP_RECORDING_ON_SILENCE {
            get {
                return ResourceManager.GetString("SETTINGS_STOP_RECORDING_ON_SILENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SETTINGS_TOOLTIP {
            get {
                return ResourceManager.GetString("SETTINGS_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech.
        /// </summary>
        public static string SPEECH {
            get {
                return ResourceManager.GetString("SPEECH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start recording.
        /// </summary>
        public static string START_RECORDING_TOOLTIP {
            get {
                return ResourceManager.GetString("START_RECORDING_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stereo.
        /// </summary>
        public static string STEREO {
            get {
                return ResourceManager.GetString("STEREO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string STOP_ON_SILENCE_DISABLED {
            get {
                return ResourceManager.GetString("STOP_ON_SILENCE_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop recording.
        /// </summary>
        public static string STOP_RECORDING_TOOLTIP {
            get {
                return ResourceManager.GetString("STOP_RECORDING_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping.
        /// </summary>
        public static string STOPPING {
            get {
                return ResourceManager.GetString("STOPPING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error!.
        /// </summary>
        public static string UNKNOWN_COPY_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_COPY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIEW.
        /// </summary>
        public static string VIEW {
            get {
                return ResourceManager.GetString("VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours.
        /// </summary>
        public static string X_HOURS {
            get {
                return ResourceManager.GetString("X_HOURS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes.
        /// </summary>
        public static string X_MINS {
            get {
                return ResourceManager.GetString("X_MINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconds.
        /// </summary>
        public static string X_SECS {
            get {
                return ResourceManager.GetString("X_SECS", resourceCulture);
            }
        }
    }
}
